### ISSUE TITLE
Use slog for logging

### ISSUE THREAD

**Issue by johanbrandhorst** [eliben/static-server#2]
Hi, cool project! I was just perusing the source and noticed that it uses `log` for its log output, but it seems to me a perfect use case for slog :). Might even allow some customization but by default a simple JSON output makes sense to me. What do you think?

**Comment by eliben** [comment]
I've considered using `slog`, but decided against it because I don't expect anyone to actually store/process the output of this server. Rather, since it's mostly useful for local testing I expect users to mostly eyeball its output in the terminal; for this use case, it wasn't clear to me that `slog` is better.

**Comment by johanbrandhorst** [comment]
Makes sense!
